### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by iCaran** [mnjm/kayal#10]
Hi, I just installed this theme today and tried to create my site, it is live here: https://icaran.github.io/theBlog/
But i have a query

---

How do I change fonts?

I tried copying the themes.css to my root directory and then change it to use devanagri font, and also put the font file in static/fonts, same as how you did with the theme, but it seems to have no effect on the site...

![Screenshot from 2024-08-03 01-41-14](https://github.com/user-attachments/assets/03d11957-e62e-4c42-8ab2-8b48288121fc)

---

Thanks for making such an awesome theme however, very useful! I also just installed the latest version with `git submodule update --remote` which you put out just yesterday.

**Comment by mnjm** [comment]
Font changes works as expected when I tested,

Changes I did,
- Download `NotoSansDevanagair-Regular.woff2` and place it in `theBlog/static/fonts/`
- Copy over `theme.css` and modify it as your SS.

Since your repo was public, I took the liberty of using it to test. You can find it [here](https://github.com/mnjm/icaran-kayal-test) with font change. (I will remove the repo once this issue is closed.)

**Comment by mnjm** [comment]
One minor thing though, is that I am preloading `Ubuntu Regular` [here](https://github.com/mnjm/kayal/blob/5604c9d8fc93e5fe335dc772d78e5334838372ee/layouts/partials/head.html#L66). This I will push a patch soon to override this

**Comment by mnjm** [comment]
> One minor thing though, is that I am preloading `Ubuntu Regular` [here](https://github.com/mnjm/kayal/blob/5604c9d8fc93e5fe335dc772d78e5334838372ee/layouts/partials/head.html#L66). This I will push a patch soon to override this

Now you can use the `preloadFonts` in `params.toml`. If you're planning to use custom font
```toml
preloadFonts = ["fonts/NotoSansDevanagair-Regular.woff2"]
```
https://github.com/mnjm/icaran-kayal-test/blob/5faf2f254810f08df73d434ec6fa99a166a3a541/config/_default/params.toml#L25

**Comment by iCaran** [comment]
Thanks, this change simplifies things.

I tried the repo you created, it's working, thanks a lot for that effort. I wonder why it wasnt working when i did it, must have made some mistake i guess...

Thankyou :)
