### ISSUE TITLE
Image and Email

### ISSUE THREAD

**Issue by iCaran** [mnjm/kayal#11]
Hi, I just installed this theme today and tried to create my site, it is live here: https://icaran.github.io/theBlog/

---

however, in params.toml, when i set the image location to top (or even left/right) `where = "top"  # Options: right, left, top`, it is displayed below the site description, see here:

![image](https://github.com/user-attachments/assets/a9eef040-b8ed-46c9-8306-f093c95e0672)

---

also, i have set the emails param, as seen here:

![image](https://github.com/user-attachments/assets/61fd493e-699c-4c2f-8fcd-d2f41cf006aa)

but it isn't visible on the page, as can be seen in the first image

---

Thanks for making such an awesome theme however, very useful! I also just installed the latest version with `git submodule update --remote` which you put out just yesterday.

**Comment by mnjm** [comment]
- Regarding image positioning, keep the home page content in `content/_index.md` file, not in headline. The headline is only for a brief, optional one-line intro, such as "Hello, Welcome to my site" or in your case it would be "Explore. Engage. Enlighten. Welcome to the garden of thoughts." Then image positioning works.
- Regarding email, Thanks for raising this. The icon should be `email`, I updated it in `assets` but failed to update in sample config file

**Comment by iCaran** [comment]
I made all the changes as you said, and it fixed all my problems. Thanks a lot again ! :)
