### ISSUE TITLE
comma in _baseof.html

### ISSUE THREAD

**Issue by iCaran** [mnjm/kayal#20]
![image](https://github.com/user-attachments/assets/1af972d6-0171-4159-b149-62cd8a5698ab)
Minor error, with no consequence i suppose. Site runs just fine with this too, however VScode doesnt like it...

**Comment by mnjm** [comment]
Ignore it, case of VScode not understanding Hugo syntax. I am actually surprised that its not throwing more errors. Maybe it understands  Hugo template code inside html but not in script :shrug:
