### ISSUE TITLE
(Feature Request) Change the content picture and video structure under /static.

### ISSUE THREAD

**Issue by abwildan** [mnjm/kayal#36]
I see kayal's structure is like this:
content
└── posts
    └── awesome-post
        ├── index.md
        ├── cover-image.jpg
        ├── img.png
        ├── video.mp4
        └── ....

But, I think it's more relevant if these pictures and videos are stored under /static like this:
└── static
    └── awesome-post
        ├── cover-image.jpg
        ├── img.png
        ├── video.mp4
        └── ....

**Comment by mnjm** [comment]
`static/` is for site wide assets. You can use page bundles to organise them, kayal/hugo already supports this. https://mnjm.github.io/kayal/page-bundles/
