### ISSUE TITLE
Timestamp and # bugs

### ISSUE THREAD

**Issue by iCaran** [mnjm/kayal#9]
Hi, I just installed this theme today and tried to create my site, it is live here: https://icaran.github.io/theBlog/

---

However, I encountered a few problems, in the markdown file for my article, when i put the date `date: "2024-08-03"`, which is today, the article dissapears both from the featured list and the posts page. 

I checked around for what it could be and I notice that for month values 01-07, it works just fine, but for values 08-12, it just dissapears from the site. So for now i just set all 'showdate' flags in the params to false, and set the date to a filler `date: "2024"`, which just reverts back to being 1st jan 2000 by default, but it doesnt show up so i guess its fine ¯\_(ツ)_/¯

---

Also, how and where exactly do I make an About page? It's not written in the docs and I'm very new to HUGO so I don't really know how to go about it, right now clicking on 'about' just takes you to 404...

---

Thanks for making such an awesome theme however, very useful! I also just installed the latest version with `git submodule update --remote` which you put out just yesterday.

---

PS: There's another issue you'll see when you visit my blog, the # work for markdown, but they are also visible in plaintext as well for some reason

**Comment by mnjm** [comment]
Regarding date,
- I recommend using the `hugo new content` command to generate new markdown files, as it will automatically populate the date field.
- Hugo does not generate content for markdown files with future dates by default. If you didn’t include the UTC offset (e.g., +05:30 for us Indians), Hugo may have defaulted to UTC+0, and therefore put your file in future.
- (or) you can place `buildFuture = true` in `config/_default/hugo.toml`.

Regarding About,
- Check [Hugo Doc](https://gohugo.io/content-management/organization/)

**Comment by mnjm** [comment]
> PS: There's another issue you'll see when you visit my blog, the # work for markdown, but they are also visible in plaintext as well for some reason

Sorry, I didn't quite understand. Could you give more info?

**Comment by iCaran** [comment]
Thankyou, the date thing did fix itself as you said yeah, thanks for that!
I'll check the about
I thought it was a bug, but the # does look good on the theme

Thanks a lot :)
